In [25]:
text=['paris paris london','london london paris']

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(text)

In [27]:
print(cv.get_feature_names())
print(x.toarray())

['london', 'paris']
[[1 2]
 [2 1]]


In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
similarity_scores=cosine_similarity(x)

In [30]:
print(similarity_scores)

[[1.  0.8]
 [0.8 1. ]]


In [31]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
data=pd.read_csv('C:\\Users\\Lenovo\\Documents\\data science\\movie_dataset.csv')
data.head(2)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   

                                                crew        director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...  Gore Verbinski  

[2 rows x 24 columns]

In [33]:
data.shape

(4803, 24)

In [34]:
data.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [35]:
features=['keywords','cast','director','genres']

In [36]:
for feature in features:
    data[feature]=data[feature].fillna('')

In [37]:
def combine_features(row):
    try:
        return row['keywords']+''+row['cast']+''+row['director']+''+row['genres']
    except:
        print('error',row)

In [38]:
data['combinedfeatures']=data.apply(combine_features,axis=1)

In [40]:
data.head(1)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity  ...                                   spoken_languages  \
0  150.437577  ...  [{"iso_639_1": "en", "name": "English"}, {"iso...   

     status                      tagline   title  vote_average vote_count  \
0  Released  Enter the World of Pandora.  Avatar           7.2      11800   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   

                                                crew       director  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...  James Cameron   

                                    combinedfeatures  
0  culture clash future space war space colony so...  

[1 rows x 25 columns]

In [43]:
count_matrix=cv.fit_transform(data['combinedfeatures'])
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [45]:
cosine_sim=cosine_similarity(count_matrix)
print(cosine_sim)

[[1.         0.03928371 0.04564355 ... 0.         0.         0.        ]
 [0.03928371 1.         0.         ... 0.0410305  0.         0.        ]
 [0.04564355 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.0410305  0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [46]:
movie_user_likes='Avatar'

In [47]:
def get_index_from_title(title):
    return data[data.title ==title]['index'].values[0]

In [48]:
def get_title_from_index(index):
    return data[data.index==index]['title'].values[0]

In [49]:
movie_index=get_index_from_title(movie_user_likes)

In [52]:
similar_movies=list(enumerate(cosine_sim[movie_index]))

In [53]:
sorted_similar_movies=sorted(similar_movies,key=lambda x:x[1],reverse=True)

In [54]:
print(sorted_similar_movies)

[(0, 0.9999999999999999), (94, 0.39167472590032015), (3158, 0.3333333333333334), (3208, 0.30463589792247125), (3730, 0.29166666666666674), (56, 0.2886751345948129), (278, 0.28577380332470415), (1531, 0.28022426915890253), (1053, 0.2738612787525831), (4593, 0.2672612419124244), (4332, 0.2611164839335468), (1473, 0.2553769592276246), (1951, 0.25000000000000006), (47, 0.24056261216234412), (1650, 0.24019223070763074), (1083, 0.2341464528954235), (3534, 0.2341464528954235), (228, 0.22821773229381925), (539, 0.22821773229381925), (2696, 0.22821773229381925), (3184, 0.22821773229381923), (2403, 0.22271770159368703), (61, 0.222717701593687), (4, 0.21759706994462233), (232, 0.2175970699446223), (541, 0.21281413268968719), (661, 0.21281413268968719), (2444, 0.21281413268968719), (1259, 0.21081851067789195), (239, 0.2083333333333334), (342, 0.20833333333333337), (1932, 0.20412414523193156), (4401, 0.20412414523193154), (150, 0.20016019225635895), (305, 0.19641855032959654), (1506, 0.192450089729

In [63]:
i=0
for movies in sorted_similar_movies:
        print (get_title_from_index(movies[0]))
        i=i+1
        if i>50:
            break     

Avatar
Guardians of the Galaxy
Alien
Star Wars: Clone Wars: Volume 1
Cargo
Star Trek Beyond
Planet of the Apes
Moonraker
Galaxy Quest
Trekkies
Silent Running
The Astronaut's Wife
Space Dogs
Star Trek Into Darkness
Wing Commander
Babylon A.D.
Galaxina
Oblivion
Titan A.E.
Jason X
The Ice Pirates
Aliens
Jupiter Ascending
John Carter
The Wolverine
Soldier
Zathura: A Space Adventure
Damnation Alley
Memoirs of an Invisible Man
Gravity
Men in Black
Sheena
The Helix... Loaded
Men in Black II
Treasure Planet
Source Code
Spaceballs
Captain America: The Winter Soldier
Lost in Space
Event Horizon
Space Chimps
Stargate: The Ark of Truth
Star Trek
Sunshine
The Thing
Mad Max: Fury Road
Red Planet
AVP: Alien vs. Predator
Star Trek: Insurrection
Alien³
Dragonball Evolution
